version: 1

workflows:
  - command: e2e-bmaas-netris-full-install
    workflow: e2e-bmaas-netris-full-install-caller.yml
    name: E2E BMaaS Netris
    description: BMaaS networking tests on the Netris infrastructure
    retestable: true
